spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: order-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083
