spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: payment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8085