spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        preserveHostHeader: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 9999